"""
Management command to simulate a complete Stream & Subject Selection session.

Runs like a real conversation: the loop continues until the session is actually
concluded — either because the LLM background check decides enough information
has been gathered (LLM-driven conclusion), or because the hard cap of
MAX_DEEPDIVE_QUESTIONS is reached.  Recommendations are generated automatically
once the session ends.

The student responses are dynamically generated by a simulated LLM agent based
on the chosen persona, so every run produces different, realistic answers.

Note: RIASEC questions have been disabled in the Stream & Subject Selection flow.

Usage:
    python manage.py simulate_domain_discovery --email test@example.com --persona arts
    python manage.py simulate_domain_discovery --email test@example.com --persona engineering
    python manage.py simulate_domain_discovery --email test@example.com --persona entrepreneurship
    python manage.py simulate_domain_discovery --email test@example.com --persona science
    python manage.py simulate_domain_discovery --email test@example.com --persona healthcare
    python manage.py simulate_domain_discovery --email test@example.com --persona random
    python manage.py simulate_domain_discovery --email test@example.com --persona arts --verbose
"""
import uuid
import time
import random
from django.core.management.base import BaseCommand
from django.utils import timezone
from apps.accounts.models import User
from apps.profiles.models import UserProfile
from domain_discovery.models import DomainSession, DomainMessage, DomainRecommendation
from domain_discovery.services import DomainDiscoveryService
# RIASEC_CONFIG import removed - RIASEC questions disabled
from domain_discovery.simulated_user_agent import SimulatedUserAgent


# Available personas (excluding 'random' which is a special case)
AVAILABLE_PERSONAS = ['arts', 'engineering', 'entrepreneurship', 'science', 'healthcare']

# Note: RIASEC preferences removed - RIASEC questions are disabled in Stream & Subject Selection


class Command(BaseCommand):
    help = 'Simulate a complete Stream & Subject Selection session with deepdive questions and recommendations'

    def add_arguments(self, parser):
        parser.add_argument(
            '--email',
            type=str,
            required=True,
            help='Email of the user to run the simulation for',
        )
        parser.add_argument(
            '--persona',
            type=str,
            choices=['arts', 'engineering', 'entrepreneurship', 'science', 'healthcare', 'random'],
            default='arts',
            help='The persona to simulate (use "random" for a randomly selected persona)',
        )
        parser.add_argument(
            '--verbose',
            action='store_true',
            help='Show detailed output for each question/answer',
        )
        parser.add_argument(
            '--dry-run',
            action='store_true',
            help='Show what would be done without making changes',
        )

    def handle(self, *args, **options):
        email = options['email']
        persona = options['persona']
        verbose = options['verbose']
        dry_run = options['dry_run']

        # Resolve 'random' to an actual persona
        if persona == 'random':
            persona = random.choice(AVAILABLE_PERSONAS)
            self.stdout.write(self.style.WARNING(f"Randomly selected persona: {persona.upper()}"))

        self.stdout.write(f"\n{'='*60}")
        self.stdout.write(f"Stream & Subject Selection Session Simulation")
        self.stdout.write(f"{'='*60}")
        self.stdout.write(f"User: {email}")
        self.stdout.write(f"Persona: {persona.upper()}")
        self.stdout.write(f"Mode: DYNAMIC (LLM-generated responses)")
        self.stdout.write(f"Ends when: LLM decides enough OR hard cap ({DomainSession.MAX_DEEPDIVE_QUESTIONS} questions)")
        self.stdout.write(f"Note: RIASEC questions disabled")
        self.stdout.write(f"Dry Run: {dry_run}")
        self.stdout.write(f"{'='*60}\n")

        # Get user
        try:
            user = User.objects.get(email=email)
        except User.DoesNotExist:
            self.stdout.write(self.style.ERROR(f"User with email {email} not found."))
            self.stdout.write("Tip: Create a user first with 'python manage.py create_test_user_profile'")
            return

        if dry_run:
            self.stdout.write(self.style.WARNING("DRY RUN - No changes will be made\n"))
            self._show_simulation_plan(persona)
            return

        # Initialize service
        service = DomainDiscoveryService()

        # Fetch the real user profile so the agent has grounded context
        from utils.profile_helpers import get_user_profile_data
        user_profile = get_user_profile_data(user)

        # Initialize the simulated user agent for dynamic responses
        self.stdout.write(self.style.HTTP_INFO("Initializing simulated user agent..."))
        try:
            simulated_agent = SimulatedUserAgent(persona=persona, user_profile=user_profile)
            self.stdout.write(self.style.SUCCESS(f"  ✓ Agent initialized with persona: {persona}"))
        except Exception as e:
            self.stdout.write(self.style.ERROR(f"  ✗ Failed to initialize agent: {e}"))
            return

        # Step 1: Create session
        self.stdout.write(self.style.HTTP_INFO("\nStep 1: Creating new session..."))
        session = service.create_session(user)
        self.stdout.write(self.style.SUCCESS(f"  ✓ Session created: {session.session_id}"))
        self.stdout.write("  Note: Starting directly with deepdive questions (RIASEC disabled)")

        # Step 2: Converse until the session ends naturally
        # The loop mirrors what happens in a real session:
        #   - After MIN_DEEPDIVE_QUESTIONS (15), a background LLM thread evaluates whether
        #     to conclude.  On the next user turn process_message() picks that up and sets
        #     is_complete=True.
        #   - If the LLM never concludes early, the hard cap (MAX_DEEPDIVE_QUESTIONS = 30)
        #     fires inside process_message() instead.
        # We also add a short sleep once the minimum threshold is passed to give the
        # background conclusion thread time to write back to the DB.
        self.stdout.write(self.style.HTTP_INFO(
            f"\nStep 2: Running conversation "
            f"(min {DomainSession.MIN_DEEPDIVE_QUESTIONS}, max {DomainSession.MAX_DEEPDIVE_QUESTIONS} questions)..."
        ))
        self.stdout.write("  Loop ends on LLM-driven conclusion or hard cap — just like a real session.")

        question_num = 0
        conclusion_reason = 'unknown'

        while True:
            # Refresh session state from DB — picks up any background conclusion check
            # that may have set should_conclude / updated total_steps.
            session.refresh_from_db()

            if session.is_completed:
                conclusion_reason = 'background-conclusion (detected before next turn)'
                break

            # Get the latest bot question
            messages = service.get_session_messages(session)
            bot_messages = [m for m in messages if m['type'] == 'bot']

            if bot_messages:
                last_question = bot_messages[-1]['content']
                response_text = simulated_agent.generate_response(last_question)
            else:
                response_text = "I find this topic really interesting and would love to explore it more."
                last_question = '(no question yet)'

            question_num += 1

            if verbose:
                self.stdout.write(f"\n  [{question_num}] Bot: {last_question[:200]}")
                self.stdout.write(f"       You: {response_text[:200]}")
            else:
                self.stdout.write(f"  Turn {question_num} | step {session.current_step}/{session.total_steps}")

            # Send the answer to the real service (same code path as production)
            response = service.process_message(session, response_text)
            session.refresh_from_db()

            if response.get('is_complete'):
                if session.current_step >= DomainSession.MAX_DEEPDIVE_QUESTIONS:
                    conclusion_reason = f'hard cap ({DomainSession.MAX_DEEPDIVE_QUESTIONS} questions)'
                else:
                    conclusion_reason = 'LLM-driven conclusion'
                # Display the concluding bot message
                concluding_msg = response.get('bot_response', '')
                if concluding_msg:
                    self.stdout.write(self.style.SUCCESS(f"\n  Bot (concluding): {concluding_msg}"))
                break

            # Once past the minimum threshold, the background conclusion-check thread
            # has been launched.  In a real conversation the user takes 10-30 s to reply,
            # giving that thread plenty of time.  Here we poll until it writes its result
            # back to the DB (or we time out and let process_message handle it next turn).
            if session.current_step >= DomainSession.MIN_DEEPDIVE_QUESTIONS:
                self._wait_for_conclusion_check(session, timeout=45)

        self.stdout.write(self.style.SUCCESS(
            f"\n  ✓ Session concluded after {question_num} turns — reason: {conclusion_reason}"
        ))
        self.stdout.write(f"    Final step: {session.current_step}/{session.total_steps}")
        self.stdout.write(f"    Deepdive completed: {session.deepdive_completed}")
        self.stdout.flush()

        # Step 3: Generate recommendations now that the session is complete
        self.stdout.write(self.style.HTTP_INFO("\nStep 3: Generating recommendations..."))
        self.stdout.flush()
        try:
            recommendations = service.generate_recommendations(session)
            self.stdout.write(self.style.SUCCESS(f"  ✓ Generated {len(recommendations)} recommendations\n"))
            for rec in recommendations:
                self.stdout.write(f"  Rank {rec.rank}: {rec.domain_title}")
                self.stdout.write(f"    Category: {rec.category}")
                self.stdout.write(f"    Match: {rec.match_percentage}%")
                self.stdout.write(f"    Key Interests: {', '.join(rec.key_interests[:3])}")
                self.stdout.write(f"    Sub-domains: {', '.join(rec.sub_domains[:3])}")
                self.stdout.write(f"    Why: {rec.why_recommended[:100]}...")
                self.stdout.write("")
        except Exception as e:
            import traceback
            self.stdout.write(self.style.ERROR(f"  ✗ Error generating recommendations: {str(e)}"))
            self.stderr.write(traceback.format_exc())

        # Final summary
        self.stdout.write(f"\n{'='*60}")
        self.stdout.write(self.style.SUCCESS("Simulation Complete!"))
        self.stdout.write(f"{'='*60}")
        self.stdout.write(f"  Session ID: {session.session_id}")
        self.stdout.write(f"  User: {user.email}")
        self.stdout.write(f"  Persona: {persona}")
        self.stdout.write(f"  Messages: {DomainMessage.objects.filter(session=session).count()}")
        self.stdout.write(f"  Recommendations: {DomainRecommendation.objects.filter(session=session).count()}")
        self.stdout.write("")

    def _wait_for_conclusion_check(self, session, timeout: int = 45):
        """Poll the DB until the background conclusion-check thread writes its result
        (metadata.should_conclude is set) or total_steps is updated, or timeout expires.

        In a real session the user takes ~10-30 s to type the next message, so the
        background LLM call always finishes in time.  In simulation we must wait
        explicitly so we don't race ahead and miss the conclusion signal.
        """
        poll_interval = 1  # seconds between DB checks
        elapsed = 0
        step_at_launch = session.current_step

        while elapsed < timeout:
            time.sleep(poll_interval)
            elapsed += poll_interval
            session.refresh_from_db()

            # Background thread wrote metadata — conclusion decision is ready
            if session.metadata and 'should_conclude' in session.metadata:
                last_checked = session.metadata.get('last_checked_step', -1)
                if last_checked >= step_at_launch:
                    if session.metadata['should_conclude']:
                        self.stdout.write(
                            self.style.WARNING(
                                f"    [wait] Conclusion check done after {elapsed}s — should_conclude=True"
                            )
                        )
                    else:
                        self.stdout.write(
                            f"    [wait] Conclusion check done after {elapsed}s — continue"
                        ) if elapsed > 3 else None
                    return

            # Background thread already flipped total_steps (is_completed now True)
            if session.is_completed:
                self.stdout.write(
                    self.style.WARNING(f"    [wait] Session marked complete after {elapsed}s")
                )
                return

        self.stdout.write(
            self.style.WARNING(f"    [wait] Conclusion check timed out after {timeout}s — proceeding anyway")
        )

    def _show_simulation_plan(self, persona):
        """Show what the simulation would do (for dry run)"""
        from domain_discovery.simulated_user_agent import PERSONA_ENHANCEMENTS

        persona_data = PERSONA_ENHANCEMENTS.get(persona, PERSONA_ENHANCEMENTS['default'])

        self.stdout.write(f"Persona: {persona.upper()}")
        self.stdout.write(f"Speaking Style: {persona_data.get('speaking_style', 'natural')}")

        self.stdout.write(f"\nSimulation Plan:")
        self.stdout.write(f"  1. Create new Stream & Subject Selection session")
        self.stdout.write(f"  2. Loop: answer questions until session.is_complete fires")
        self.stdout.write(f"       - LLM-driven early conclusion (after min={DomainSession.MIN_DEEPDIVE_QUESTIONS} questions)")
        self.stdout.write(f"       - Hard cap at max={DomainSession.MAX_DEEPDIVE_QUESTIONS} questions")
        self.stdout.write(f"  3. Generate recommendations automatically on completion")
        self.stdout.write(f"\nNote: RIASEC questions have been disabled in Stream & Subject Selection")
        self.stdout.write(f"\nResponses are dynamically generated by an LLM agent — different every run.")
        self.stdout.write("")
