# Generated by Django 5.2.12 on 2026-04-28 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0029_alter_grademoduleautoassignment_module_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CollegeSelectorSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_id",
                    models.CharField(db_index=True, max_length=100, unique=True),
                ),
                ("current_step", models.IntegerField(default=0)),
                ("total_steps", models.IntegerField(default=20)),
                (
                    "current_phase",
                    models.CharField(
                        choices=[
                            ("preferences", "Preferences"),
                            ("conversation", "Conversation"),
                            ("completed", "Completed"),
                        ],
                        default="preferences",
                        max_length=20,
                    ),
                ),
                (
                    "preferences",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Static questionnaire answers",
                    ),
                ),
                ("preferences_completed", models.BooleanField(default=False)),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="AI-generated observations about the student's preferences to guide conversation",
                    ),
                ),
                (
                    "token_usage",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Accumulated LLM token usage",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, help_text="Session metadata"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="college_selector_sessions",
                        to="accounts.user",
                    ),
                ),
            ],
            options={
                "verbose_name": "College Selector Session",
                "verbose_name_plural": "College Selector Sessions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CollegeRecommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("university_name", models.CharField(max_length=300)),
                (
                    "website_url",
                    models.URLField(blank=True, default="", max_length=500),
                ),
                ("location", models.CharField(blank=True, default="", max_length=200)),
                ("country", models.CharField(blank=True, default="", max_length=100)),
                (
                    "deadlines",
                    models.JSONField(
                        blank=True, default=dict, help_text="EA/ED/RD/Rolling deadlines"
                    ),
                ),
                (
                    "degree_and_major",
                    models.CharField(blank=True, default="", max_length=300),
                ),
                (
                    "tuition_fees",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "cost_of_living",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "scholarships",
                    models.JSONField(
                        blank=True, default=list, help_text="Types & availability"
                    ),
                ),
                (
                    "academic_requirements",
                    models.JSONField(
                        blank=True, default=dict, help_text="GPA, SAT, ACT etc."
                    ),
                ),
                (
                    "additional_requirements",
                    models.JSONField(
                        blank=True, default=list, help_text="SOPs, LORs, Portfolio"
                    ),
                ),
                (
                    "university_type",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                (
                    "global_ranking",
                    models.JSONField(
                        blank=True, default=dict, help_text="QS/THE/USN rankings"
                    ),
                ),
                (
                    "acceptance_rate",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                (
                    "application_fee",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("tests_required", models.JSONField(blank=True, default=list)),
                (
                    "post_study_work_visa",
                    models.CharField(blank=True, default="", max_length=300),
                ),
                (
                    "employment_rate",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "language",
                    models.CharField(blank=True, default="English", max_length=100),
                ),
                (
                    "campus_type",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                ("intl_student_support", models.TextField(blank=True, default="")),
                (
                    "fit_category",
                    models.CharField(
                        choices=[
                            ("reach", "Reach"),
                            ("match", "Match"),
                            ("safe", "Safe"),
                        ],
                        default="match",
                        max_length=10,
                    ),
                ),
                ("match_percentage", models.IntegerField(default=0)),
                ("description", models.TextField(blank=True, default="")),
                ("rank", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendations",
                        to="college_selector.collegeselectorsession",
                    ),
                ),
            ],
            options={
                "verbose_name": "College Recommendation",
                "verbose_name_plural": "College Recommendations",
                "ordering": ["rank", "-match_percentage"],
            },
        ),
        migrations.CreateModel(
            name="CollegeSelectorMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message_id", models.CharField(max_length=100, unique=True)),
                (
                    "type",
                    models.CharField(
                        choices=[("bot", "Bot"), ("user", "User")], max_length=10
                    ),
                ),
                ("content", models.TextField()),
                (
                    "medium",
                    models.CharField(
                        choices=[("text", "Text"), ("voice", "Voice")],
                        default="text",
                        max_length=10,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="college_selector.collegeselectorsession",
                    ),
                ),
            ],
            options={
                "verbose_name": "College Selector Message",
                "verbose_name_plural": "College Selector Messages",
                "ordering": ["timestamp"],
                "indexes": [
                    models.Index(
                        fields=["session", "timestamp"],
                        name="college_sel_session_46811a_idx",
                    ),
                    models.Index(
                        fields=["session", "type"],
                        name="college_sel_session_ecd753_idx",
                    ),
                ],
            },
        ),
    ]
