# Generated by Django 5.2.12 on 2026-05-14 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college_selector', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collegerecommendation',
            name='fit_reasoning',
            field=models.TextField(blank=True, default='', help_text='Explanation of why this college is categorized as reach/match/safe for the student'),
        ),
    ]
