# Generated by Django 5.2.12 on 2026-05-14 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college_selector', '0002_add_fit_reasoning_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='collegerecommendation',
            name='suggested_deadline',
            field=models.CharField(blank=True, default='', help_text='Recommended application round and date for the student', max_length=200),
        ),
    ]
