# Generated by Django 6.0 on 2026-03-20 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_drop_removed_app_tables"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("student", "Student"),
                    ("school", "School"),
                    ("superadmin", "Superadmin"),
                ],
                default="student",
                max_length=20,
            ),
        ),
    ]
