# Generated by Django 6.0 on 2026-03-27 08:37

from django.db import migrations


def migrate_school_to_schooladmin(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    User.objects.filter(role="school").update(role="schooladmin")


def reverse_migration(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    User.objects.filter(role="schooladmin").update(role="school")


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_school_alter_user_role_notification_deadline_and_more"),
    ]

    operations = [
        migrations.RunPython(migrate_school_to_schooladmin, reverse_migration),
    ]
