# Generated by Django 5.2.12 on 2026-04-05 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0012_user_academic_level_grade_level"),
    ]

    operations = [
        migrations.AddField(
            model_name="schoolpayment",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="userpayment",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
