# Generated by Django 5.2.12 on 2026-04-05 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0013_add_metadata_to_payments"),
    ]

    operations = [
        migrations.AddField(
            model_name="schoolmodulesubscription",
            name="payment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="subscriptions",
                to="accounts.schoolpayment",
            ),
        ),
        migrations.AddField(
            model_name="usermodulesubscription",
            name="payment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="subscriptions",
                to="accounts.userpayment",
            ),
        ),
    ]
