# Generated by Django 5.2.12 on 2026-04-05 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0014_add_payment_fk_to_subscriptions"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="schoolpayment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "pending")),
                fields=("school",),
                name="unique_pending_school_payment",
            ),
        ),
        migrations.AddConstraint(
            model_name="userpayment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "pending")),
                fields=("user",),
                name="unique_pending_user_payment",
            ),
        ),
    ]
