# Generated by Django 5.2.12 on 2026-04-10 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0019_add_expiry_date_quantity_to_payments"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schoolmodulesubscription",
            name="module_name",
            field=models.CharField(
                choices=[
                    ("essay_brainstormer", "Essay Brainstormer"),
                    ("essay_evaluator", "Essay Evaluator"),
                    ("college_selector", "College Selector"),
                    ("degree_selector", "Degree Selector"),
                    ("interview_prep", "Interview Prep"),
                    ("resume_builder", "Resume Builder"),
                    ("career_discovery", "Career & Degree Selection"),
                    ("domain_discovery", "Stream & Subject Selection"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="usermodulesubscription",
            name="module_name",
            field=models.CharField(
                choices=[
                    ("essay_brainstormer", "Essay Brainstormer"),
                    ("essay_evaluator", "Essay Evaluator"),
                    ("college_selector", "College Selector"),
                    ("degree_selector", "Degree Selector"),
                    ("interview_prep", "Interview Prep"),
                    ("resume_builder", "Resume Builder"),
                    ("career_discovery", "Career & Degree Selection"),
                    ("domain_discovery", "Stream & Subject Selection"),
                ],
                max_length=30,
            ),
        ),
    ]
