# Generated by Django 5.2.12 on 2026-04-17 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0020_alter_schoolmodulesubscription_module_name_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="schoolmodulesubscription",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="usermodulesubscription",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="usermodulesubscription",
            name="assigned_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="module_assignments_made",
                to="accounts.user",
            ),
        ),
        migrations.AddField(
            model_name="usermodulesubscription",
            name="school_subscription",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="student_assignments",
                to="accounts.schoolmodulesubscription",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="academic_level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("high_school", "High School (8th–12th grade)"),
                    ("undergraduate", "College/Undergraduate"),
                    ("postgraduate", "Postgraduate"),
                    ("professional", "Working/Completed College"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="usermodulesubscription",
            name="source",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("payment", "Payment"),
                    ("school_assignment", "School Assignment"),
                    ("other", "Other"),
                ],
                default="admin",
                max_length=20,
            ),
        ),
    ]
