# Generated by Django 5.2.12 on 2026-04-13 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0020_alter_schoolmodulesubscription_module_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="academic_level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("high_school", "High School (8th–12th grade)"),
                    ("undergraduate", "College/Undergraduate"),
                    ("postgraduate", "Postgraduate"),
                    ("professional", "Working/Completed College"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
