# Generated by Django 5.2.12 on 2026-04-17 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0021_remove_unique_add_assignment_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="GradeModuleAutoAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("grade_level", models.CharField(max_length=20)),
                (
                    "module_name",
                    models.CharField(
                        choices=[
                            ("essay_brainstormer", "Essay Brainstormer"),
                            ("essay_evaluator", "Essay Evaluator"),
                            ("college_selector", "College Selector"),
                            ("degree_selector", "Degree Selector"),
                            ("interview_prep", "Interview Prep"),
                            ("resume_builder", "Resume Builder"),
                            ("career_discovery", "Career & Degree Selection"),
                            ("domain_discovery", "Stream & Subject Selection"),
                        ],
                        max_length=30,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="auto_assignments_created",
                        to="accounts.user",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grade_auto_assignments",
                        to="accounts.school",
                    ),
                ),
                (
                    "school_subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="auto_assignments",
                        to="accounts.schoolmodulesubscription",
                    ),
                ),
            ],
            options={
                "unique_together": {("school", "grade_level", "module_name")},
            },
        ),
    ]
