# Generated by Django 5.2.12 on 2026-04-19 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0021_alter_user_academic_level"),
        ("accounts", "0022_grade_module_auto_assignment"),
    ]

    operations = []
