# Generated by Django 5.2.12 on 2026-04-20 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_merge_20260420_0110'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='counselor_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='user',
            name='counselor_comment_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='parent_student_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='user',
            name='parent_student_comment_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
