# Generated by Django 5.2.12 on 2026-04-22 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0024_user_counselor_comment_and_more"),
        ("accounts", "0024_user_force_password_change"),
    ]

    operations = []
