# Generated by Django 5.2.12 on 2026-04-23 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0026_convert_modules_purchased_format"),
    ]

    operations = [
        migrations.AlterField(
            model_name="grademoduleautoassignment",
            name="module_name",
            field=models.CharField(
                choices=[
                    ("career_discovery", "Career & Degree Selection"),
                    ("domain_discovery", "Stream & Subject Selection"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="schoolmodulesubscription",
            name="module_name",
            field=models.CharField(
                choices=[
                    ("career_discovery", "Career & Degree Selection"),
                    ("domain_discovery", "Stream & Subject Selection"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="usermodulesubscription",
            name="module_name",
            field=models.CharField(
                choices=[
                    ("career_discovery", "Career & Degree Selection"),
                    ("domain_discovery", "Stream & Subject Selection"),
                ],
                max_length=30,
            ),
        ),
    ]
