# Generated by Django 5.2.12 on 2026-04-28 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0027_alter_grademoduleautoassignment_module_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="school",
            name="currency",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.CreateModel(
            name="ModulePricing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "module_name",
                    models.CharField(
                        choices=[
                            ("career_discovery", "Career & Degree Selection"),
                            ("domain_discovery", "Stream & Subject Selection"),
                        ],
                        max_length=30,
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("currency_variants", models.JSONField(blank=True, default=dict)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "school",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="module_pricing",
                        to="accounts.school",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="module_pricing",
                        to="accounts.user",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(
                            ("school__isnull", True), ("user__isnull", True)
                        ),
                        fields=("module_name",),
                        name="unique_global_module_pricing",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(
                            ("school__isnull", False), ("user__isnull", True)
                        ),
                        fields=("module_name", "school"),
                        name="unique_school_module_pricing",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(
                            ("school__isnull", True), ("user__isnull", False)
                        ),
                        fields=("module_name", "user"),
                        name="unique_user_module_pricing",
                    ),
                ],
            },
        ),
    ]
