# Generated by Django 5.2.12 on 2026-05-13 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_add_order_id_remove_pending_constraints'),
        ('accounts', '0030_coupon'),
    ]

    operations = [
    ]
