# Generated by Django 5.2.12 on 2026-05-19 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_merge_20260513_1654'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50, unique=True)),
                ('label', models.CharField(max_length=100)),
                ('icon', models.CharField(default='briefcase', max_length=50)),
                ('color', models.CharField(default='bg-purple-100 text-purple-700', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
