# Generated by Django 5.2.12 on 2026-06-09 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_alter_user_terms_accepted_activitylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodulesubscription',
            name='reminder_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usermodulesubscription',
            name='reminder_last_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
