# Generated by Django 5.2.12 on 2026-06-11 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_usermodulesubscription_reminder_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modulepricing',
            name='module_name',
            field=models.CharField(max_length=30),
        ),
    ]
