# Generated by Django 5.2.12 on 2026-06-11 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0035_alter_modulepricing_module_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulepricing',
            name='dummy_test',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
