# Generated by Django 5.2.12 on 2026-06-11 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0036_modulepricing_dummy_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modulepricing',
            name='dummy_test',
        ),
        migrations.AddField(
            model_name='modulepricing',
            name='label_override',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
