# Generated by Django 5.2.12 on 2026-06-12 12:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0037_remove_modulepricing_dummy_test_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grademoduleautoassignment',
            name='module_name',
            field=models.CharField(choices=[('college_selector', 'College Selector'), ('resume_builder', 'Resume Builder'), ('career_discovery', 'Career & Degree Selection'), ('domain_discovery', 'Stream & Subject Selection')], max_length=30),
        ),
        migrations.AlterField(
            model_name='schoolmodulesubscription',
            name='module_name',
            field=models.CharField(choices=[('college_selector', 'College Selector'), ('resume_builder', 'Resume Builder'), ('career_discovery', 'Career & Degree Selection'), ('domain_discovery', 'Stream & Subject Selection')], max_length=30),
        ),
        migrations.AlterField(
            model_name='schoolpayment',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='usermodulesubscription',
            name='module_name',
            field=models.CharField(choices=[('college_selector', 'College Selector'), ('resume_builder', 'Resume Builder'), ('career_discovery', 'Career & Degree Selection'), ('domain_discovery', 'Stream & Subject Selection')], max_length=30),
        ),
        migrations.AlterField(
            model_name='userpayment',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
