# Generated by Django 6.0 on 2026-01-11 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=200)),
                ('state', models.CharField(blank=True, max_length=200, null=True)),
                ('country', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['country', 'state', 'city'],
                'unique_together': {('city', 'state', 'country')},
            },
        ),
    ]
