# Generated by Django 6.0 on 2026-02-06 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("career_discovery", "0004_careersession_notes"),
    ]

    operations = [
        migrations.AddField(
            model_name="careersession",
            name="token_usage",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Accumulated LLM token usage per category and totals for this session",
            ),
        ),
    ]
