# Generated by Django 6.0 on 2026-03-16 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("career_discovery", "0008_careermessage_medium"),
    ]

    operations = [
        migrations.AddField(
            model_name="careerrecommendation",
            name="related_subjects",
            field=models.JSONField(default=list),
        ),
    ]
