# Generated by Django 6.0

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("career_discovery", "0009_add_related_subjects_to_career_recommendation"),
    ]

    operations = [
        migrations.AddField(
            model_name="careerrecommendation",
            name="degrees",
            field=models.JSONField(default=list),
        ),
    ]
