# Generated by Django 5.2.12 on 2026-04-14 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("career_discovery", "0010_add_degrees_to_career_recommendation"),
    ]

    operations = [
        migrations.AddField(
            model_name="careerrecommendation",
            name="degree_decision_filter",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Decision rules to help choose between degrees (If you enjoy X → choose Y)",
            ),
        ),
        migrations.AddField(
            model_name="careerrecommendation",
            name="degree_fit_scores",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Fit scores (1-5 stars) for key degrees with justification",
            ),
        ),
        migrations.AddField(
            model_name="careerrecommendation",
            name="degree_pathways",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Ranked degree pathways (Core/Alternate/Differentiated) with degrees and reasoning",
            ),
        ),
    ]
