# Generated by Django 5.2.12 on 2026-06-05 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career_discovery', '0012_consolidate_degrees'),
    ]

    operations = [
        migrations.AddField(
            model_name='careerrecommendation',
            name='feasibility',
            field=models.JSONField(blank=True, default=dict, help_text='Feasibility metric: {level: High|Medium|Low, reason: str}'),
        ),
        migrations.AddField(
            model_name='careerrecommendation',
            name='skill_gaps',
            field=models.JSONField(blank=True, default=list, help_text="Top 5 personalised skill gaps for this career given the student's profile"),
        ),
    ]
