from django.urls import path
from .views import *  # pylint: disable=unused-wildcard-import, wildcard-import
from .views import StudentCommentView, AdminSendEmailView, StudentSendCounselorEmailView
from .payment_views import (
    StudentCheckoutView, StudentPaymentsView,
    SchoolCheckoutView, SchoolPaymentsHistoryView,
    SchoolSubscriptionsView, StudentSubscriptionsView,
    SchoolLedgerView, StudentLedgerView,
    SchoolStudentModuleAssignView, SchoolStudentModuleRevokeView,
    SchoolModuleReminderView,
    GradeAutoAssignView, GradeAutoAssignDeleteView,
    PaymentStatusView,
    GuestPaymentStatusView,
    PaymentReturnVerifyView,
    ModulePricingPublicView,
    AdminCouponListCreateView,
    AdminCouponDetailView,
    CouponValidatePublicView,
    StudentInvoiceDownloadView,
    SchoolInvoiceDownloadView,
)
from .payment_webhook import HDFCWebhookView

urlpatterns = [
    path("signup/", SignupView.as_view()),
    path("verify/", OTPVerifyView.as_view()),
    path("login/", LoginView.as_view()),
    path("password-reset/request/", PasswordResetRequestView.as_view()),
    path("password-reset/confirm/", PasswordResetConfirmView.as_view()),
    path("accept-terms/", AcceptTermsView.as_view()),
    path("change-password/", ChangePasswordView.as_view()),
    path("me/", MeView.as_view()),
    path("my-modules/", MyModulesView.as_view()),
    path("module-choices/", ModuleChoicesView.as_view()),
    path("custom-modules/", CustomModuleListCreateView.as_view()),
    path("custom-modules/<str:value>/", CustomModuleDetailView.as_view()),
    path("me/checkout/", StudentCheckoutView.as_view()),
    path("me/payments/", StudentPaymentsView.as_view()),
    path("me/payments/<int:payment_id>/invoice/", StudentInvoiceDownloadView.as_view()),
    path("me/subscriptions/", StudentSubscriptionsView.as_view()),
    path("me/ledger/", StudentLedgerView.as_view()),
    path("me/comments/", StudentCommentView.as_view()),
    path("me/send-counselor-email/", StudentSendCounselorEmailView.as_view()),
    path("payment/<int:payment_id>/status/", PaymentStatusView.as_view()),
    path("payment/<int:payment_id>/guest-status/", GuestPaymentStatusView.as_view()),
    # HDFC return — unauthenticated, called by the frontend Route Handler
    path("payment/return-verify/<str:order_id>/<str:payment_type>/", PaymentReturnVerifyView.as_view()),
    # School-admin self-service checkout
    path("school/checkout/", SchoolCheckoutView.as_view()),
    path("school/payments/", SchoolPaymentsHistoryView.as_view()),
    path("school/payments/<int:payment_id>/invoice/", SchoolInvoiceDownloadView.as_view()),
    path("school/subscriptions/", SchoolSubscriptionsView.as_view()),
    path("school/ledger/", SchoolLedgerView.as_view()),
    path("school/assign-modules/", SchoolStudentModuleAssignView.as_view()),
    path("school/assign-modules/<int:assignment_id>/revoke/", SchoolStudentModuleRevokeView.as_view()),
    path("school/module-reminder/", SchoolModuleReminderView.as_view()),
    path("school/grade-auto-assign/", GradeAutoAssignView.as_view()),
    path("school/grade-auto-assign/<int:rule_id>/", GradeAutoAssignDeleteView.as_view()),
    path("settings/", SettingsView.as_view()),
    path("admin/dashboard/", AdminDashboardView.as_view()),
    path("admin/users/", AdminUsersView.as_view()),
    path("admin/users/bulk-import/validate/", AdminBulkImportValidateView.as_view()),
    path("admin/users/bulk-import/", AdminBulkImportView.as_view()),
    path("admin/users/<int:user_id>/", AdminUserDetailView.as_view()),
    path("admin/users/<int:user_id>/modules/", AdminUserModuleView.as_view()),
    path("admin/users/<int:user_id>/modules/<int:sub_id>/", AdminUserModuleDetailView.as_view()),
    path("admin/users/<int:user_id>/comments/", AdminUserCommentView.as_view()),
    path("admin/users/<int:user_id>/send-email/", AdminSendEmailView.as_view()),
    path("admin/sessions/<str:module>/<str:session_id>/messages/", AdminSessionMessagesView.as_view()),
    path("admin/sessions/<str:module>/<str:session_id>/report/", AdminSessionReportView.as_view()),
    path("module-prices/", ModulePricingPublicView.as_view()),
    path("academic-levels/", AcademicLevelsView.as_view()),
    # HDFC webhook — public endpoint, signature-verified
    path("webhooks/hdfc/", HDFCWebhookView.as_view(), name="hdfc-webhook"),
    path("admin/coupons/", AdminCouponListCreateView.as_view()),
    path("admin/coupons/<int:coupon_id>/", AdminCouponDetailView.as_view()),
    path("coupons/validate/", CouponValidatePublicView.as_view()),
]
