# Generated by Django 6.0 on 2026-01-03 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DomainSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_id",
                    models.CharField(db_index=True, max_length=100, unique=True),
                ),
                ("current_step", models.IntegerField(default=0)),
                ("total_steps", models.IntegerField(default=8)),
                (
                    "current_phase",
                    models.CharField(
                        choices=[
                            ("exploration", "Interest Exploration"),
                            ("mapping", "Domain Mapping"),
                        ],
                        default="exploration",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="domain_sessions",
                        to="accounts.user",
                    ),
                ),
            ],
            options={
                "verbose_name": "Domain Session",
                "verbose_name_plural": "Domain Sessions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DomainRecommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("domain_title", models.CharField(max_length=200)),
                ("category", models.CharField(blank=True, max_length=100)),
                ("match_percentage", models.IntegerField(default=0)),
                ("key_interests", models.JSONField(default=list)),
                ("sub_domains", models.JSONField(default=list)),
                ("related_subjects", models.JSONField(default=list)),
                ("description", models.TextField(blank=True)),
                ("why_recommended", models.TextField(blank=True)),
                ("exploration_activities", models.JSONField(default=list)),
                ("potential_careers", models.JSONField(default=list)),
                ("rank", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendations",
                        to="domain_discovery.domainsession",
                    ),
                ),
            ],
            options={
                "verbose_name": "Domain Recommendation",
                "verbose_name_plural": "Domain Recommendations",
                "ordering": ["rank", "-match_percentage"],
            },
        ),
        migrations.CreateModel(
            name="DomainMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message_id", models.CharField(max_length=100, unique=True)),
                (
                    "type",
                    models.CharField(
                        choices=[("bot", "Bot"), ("user", "User")], max_length=10
                    ),
                ),
                ("content", models.TextField()),
                ("step_number", models.IntegerField(default=0)),
                ("phase", models.CharField(default="exploration", max_length=20)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="domain_discovery.domainsession",
                    ),
                ),
            ],
            options={
                "verbose_name": "Domain Message",
                "verbose_name_plural": "Domain Messages",
                "ordering": ["timestamp"],
            },
        ),
    ]
