# Generated by Django 6.0 on 2026-01-15 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("domain_discovery", "0003_alter_domainsession_total_steps"),
    ]

    operations = [
        migrations.AddField(
            model_name="domainrecommendation",
            name="riasec_scores",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
