# Generated by Django migration

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain_discovery', '0005_add_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='domainsession',
            name='riasec_scores',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
