# Generated by Django migration

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domain_discovery', '0006_domainsession_riasec_scores'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='domainrecommendation',
            name='riasec_scores',
        ),
    ]
