# Generated by Django 6.0 on 2026-01-15 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("domain_discovery", "0007_remove_domainrecommendation_riasec_scores"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="domainmessage",
            new_name="domain_disc_session_0ed7d5_idx",
            old_name="domain_disc_session_timestamp_idx",
        ),
        migrations.RenameIndex(
            model_name="domainmessage",
            new_name="domain_disc_session_743985_idx",
            old_name="domain_disc_session_type_idx",
        ),
    ]
