# Generated by Django 6.0 on 2026-01-19 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "domain_discovery",
            "0008_rename_domain_disc_session_timestamp_idx_domain_disc_session_0ed7d5_idx_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="domainmessage",
            name="phase",
        ),
        migrations.RemoveField(
            model_name="domainmessage",
            name="step_number",
        ),
        migrations.RemoveField(
            model_name="domainsession",
            name="current_phase",
        ),
        migrations.RemoveField(
            model_name="domainsession",
            name="total_steps",
        ),
        migrations.AddField(
            model_name="domainmessage",
            name="choices",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="domainmessage",
            name="question_type",
            field=models.CharField(
                choices=[
                    ("riasec", "RIASEC Question"),
                    ("deepdive", "Deep Dive Question"),
                    ("general", "General Message"),
                ],
                default="general",
                max_length=20,
            ),
        ),
    ]
