# Generated by Django 6.0 on 2026-01-30 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("domain_discovery", "0009_remove_domainmessage_phase_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="domainsession",
            name="total_steps",
            field=models.IntegerField(default=15),
        ),
    ]
