# Generated by Django 6.0 on 2026-01-30 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("domain_discovery", "0010_domainsession_total_steps"),
    ]

    operations = [
        migrations.AlterField(
            model_name="domainsession",
            name="total_steps",
            field=models.IntegerField(default=25),
        ),
    ]
