# Generated by Django 6.0 on 2026-02-17 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("domain_discovery", "0014_domainsession_metadata"),
    ]

    operations = [
        migrations.AlterField(
            model_name="domainsession",
            name="total_steps",
            field=models.IntegerField(default=35),
        ),
    ]
