# Generated by Django 6.0 on 2026-03-05 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("domain_discovery", "0016_delete_predefineddomain"),
    ]

    operations = [
        migrations.AlterField(
            model_name="domainsession",
            name="total_steps",
            field=models.IntegerField(default=30),
        ),
    ]
