# Generated by Django 5.2.12 on 2026-04-14 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("domain_discovery", "0018_domainmessage_medium"),
    ]

    operations = [
        migrations.AddField(
            model_name="domainrecommendation",
            name="subject_combination_pathways",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="2-3 recommended subject combinations with pathway names, career outcomes, and student fit",
            ),
        ),
        migrations.AddField(
            model_name="domainrecommendation",
            name="subject_importance",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Subject importance classification: core, supporting, optional with reasons",
            ),
        ),
        migrations.AddField(
            model_name="domainrecommendation",
            name="subject_relevance",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Personalized explanation of why each subject matters for this student (subject → reason)",
            ),
        ),
    ]
