# Generated by Django 5.2.12 on 2026-04-17 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("domain_discovery", "0019_enhanced_report_sections"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="domainrecommendation",
            name="subject_combination_pathways",
        ),
        migrations.RemoveField(
            model_name="domainrecommendation",
            name="subject_importance",
        ),
        migrations.RemoveField(
            model_name="domainrecommendation",
            name="subject_relevance",
        ),
    ]
