# Generated by Django 5.2.12 on 2026-04-19 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("domain_discovery", "0019_modulereview"),
        ("domain_discovery", "0020_consolidate_related_subjects"),
    ]

    operations = []
