# Generated by Hand to fix incorrect foreign key constraint pointing to auth_user instead of accounts_user

from django.db import migrations

def forwards_func(apps, schema_editor):
    if schema_editor.connection.vendor == 'sqlite':
        return
    schema_editor.execute(
        "ALTER TABLE domain_discovery_modulereview "
        "DROP CONSTRAINT IF EXISTS domain_discovery_modulereview_user_id_2757b665_fk_auth_user_id;"
    )
    schema_editor.execute(
        "ALTER TABLE domain_discovery_modulereview "
        "ADD CONSTRAINT domain_discovery_modulereview_user_id_fk_accounts_user "
        "FOREIGN KEY (user_id) REFERENCES accounts_user(id) "
        "DEFERRABLE INITIALLY DEFERRED;"
    )

def reverse_func(apps, schema_editor):
    if schema_editor.connection.vendor == 'sqlite':
        return
    schema_editor.execute(
        "ALTER TABLE domain_discovery_modulereview "
        "DROP CONSTRAINT IF EXISTS domain_discovery_modulereview_user_id_fk_accounts_user;"
    )
    schema_editor.execute(
        "ALTER TABLE domain_discovery_modulereview "
        "ADD CONSTRAINT domain_discovery_modulereview_user_id_2757b665_fk_auth_user_id "
        "FOREIGN KEY (user_id) REFERENCES auth_user(id) "
        "DEFERRABLE INITIALLY DEFERRED;"
    )

class Migration(migrations.Migration):

    dependencies = [
        ("domain_discovery", "0021_merge_20260420_0049"),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func)
    ]
