# Generated by Django 5.2.12 on 2026-06-10 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain_discovery', '0022_fix_modulereview_user_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='domainrecommendation',
            name='feasibility',
            field=models.JSONField(blank=True, default=dict, help_text='Feasibility metric: {level: High|Medium|Low, reason: str}'),
        ),
        migrations.AddField(
            model_name='domainrecommendation',
            name='skill_gaps',
            field=models.JSONField(blank=True, default=list, help_text="Top 5 personalised skill gaps (areas of growth) for this domain given the student's profile"),
        ),
    ]
